import 'normalize.css';
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
// import localFont from "next/font/local";
import { Roboto } from 'next/font/google'
import { Metadata } from "next";
import ResponsiveDrawer from "@/components/Sidebar/Sidebar"; // Use ResponsiveDrawer instead of Sidebar
import s from './page.module.scss'; 


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ResponsiveDrawer>
              <div className={s.main_container}>
                {children}
              </div>
            </ResponsiveDrawer>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
